# -*- mode: makefile-gmake -*-
.DELETE_ON_ERROR:

include ../projdir.mk

SRC_EXAMPLES_CXX = ex1.cpp

include $(PROJ_DIR)/lib/symmFast/conf/projvariables
include $(PROJ_DIR)/lib/symmFast/conf/projrules
include $(PROJ_DIR)/lib/symmFast/conf/projconf
